"use server";

import connectToDatabase from '../../lib/mongodb';
import UserProgress from '../../models/UserProgress';

/**
 * Badge milestones configuration
 */
const BADGE_MILESTONES = {
  5: 'Beginner',
  10: 'Starter',
  15: 'Momentum Builder',
  20: 'Achiever',
  25: 'Fitness Enthusiast',
  30: 'Warrior',
  35: 'Power House',
  40: 'Iron Will',
  45: 'Unstoppable',
  50: 'Halfway Hero',
  55: 'Dedicated',
  60: 'Disciplined',
  65: 'Machine',
  70: 'Elite',
  75: 'Master',
  80: 'Legend',
  85: 'God Mode',
  90: 'Apex',
  95: 'Inhuman',
  100: 'Century King'
};

/**
 * Fetch the progress record for a specific user.
 */
export async function getProgress(userId) {
  try {
    await connectToDatabase();
    const record = await UserProgress.findOne({ userId }).lean();
    if (!record) return null;
    
    // Ensure badges array exists for frontend
    const badges = record.badges || [];
    
    // Convert Mongoose/MongoDB objects to plain JSON strings for serialization.
    return JSON.parse(JSON.stringify({
      pushupData: record.pushupData,
      badges
    }));
  } catch (error) {
    console.error(`Error fetching progress for ${userId}:`, error);
    throw new Error('Failed to fetch progress from database.');
  }
}

/**
 * Save or update the progress record for a specific user.
 */
export async function saveProgress(userId, pushupData) {
  try {
    await connectToDatabase();
    
    // Find the latest completed day
    const completedDays = pushupData.filter(d => d.isCompleted).length;
    
    // Check if a new badge should be unlocked
    let newBadge = null;
    if (completedDays > 0 && completedDays % 5 === 0) {
      newBadge = BADGE_MILESTONES[completedDays];
    }

    const updateQuery = { $set: { pushupData } };
    if (newBadge) {
      updateQuery.$addToSet = { badges: newBadge };
    }

    await UserProgress.updateOne(
      { userId },
      updateQuery,
      { upsert: true }
    );
    return { success: true };
  } catch (error) {
    console.error(`Error saving progress for ${userId}:`, error);
    throw new Error('Failed to save progress to database.');
  }
}

/**
 * Reset progress for a specific user.
 */
export async function resetProgressAction(userId) {
  try {
    await connectToDatabase();
    await UserProgress.updateOne(
      { userId },
      { 
        $set: { 
          pushupData: [], // Will be re-generated by context
          badges: [] 
        } 
      }
    );
    return { success: true };
  } catch (error) {
    console.error(`Error resetting progress for ${userId}:`, error);
    throw new Error('Failed to reset progress.');
  }
}
